name: Generate Holidays JSON Temp

on:
    workflow_dispatch: # 允许手动触发

env:
    # 保存文件夹
    OUTPUT_PATH: ${{ github.workspace }}/holidays/
    
    # 数据来源
    SOURCE: https://www.gov.cn/

    # 指定年份
    YEARS: '[2000, 2024]'

    # 数据中心文件
    DATA_CENTER_FILE: ${{ github.workspace }}/data.json

    # 在数据中心的标识
    DATA_CENTER_NAME: holidays

jobs:
    generate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.8"

            - name: Install dependencies
              working-directory: .github/holidays
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            
            - name: Get years
              id: years
              uses: actions/github-script@v6
              with:
                script: |
                  const years = JSON.parse(process.env.YEARS);
                  const current_year = years[0];
                  const next_year = years[1];
                  // 生成年份列表 current_year-next_year
                  let _years = [];
                  for (let i = current_year; i <= next_year; i++) {
                      _years.push(i);
                  }
                  
                  core.setOutput('year', _years.join(' '));


            # 获取当前年份的节假日数据
            - name: Get holidays data
              id: get_holidays
              working-directory: .github/holidays
              run: |
                  python holidays.py -y ${{ steps.years.outputs.year }} -o ${{ env.OUTPUT_PATH }}

            - name: Update JSON file
              uses: actions/github-script@v6
              with:
                  script: |
                    const { buildData, processDataUpdate } = require('.github/utils/json.js');
                    const { listFiles } = require('.github/utils/utils.js');

                    const output_path_rel = process.env.OUTPUT_PATH.replace(`${process.env.GITHUB_WORKSPACE}/`, '');
                    const path = listFiles(output_path_rel);

                    const data = buildData({
                        name: process.env.DATA_CENTER_NAME,
                        description: 'Chinese Holiday Information',
                        description_zh: '中国节假日信息',
                        path
                    });

                    processDataUpdate(process.env.DATA_CENTER_FILE, data)
                    console.log(`JSON 文件已更新：${process.env.DATA_CENTER_FILE}`);
                    
            - name: Commit and push changes
              run: |
                git config --global user.name "GitHub Actions"
                git config --global user.email "actions@github.com"
                git add ${{ env.OUTPUT_PATH }}
                git commit -m "Auto-generated JSON file [skip ci]"
                git add ${{ env.DATA_CENTER_FILE }}
                git commit -m "Update data center file [skip ci]"
                git push
              