name: Generate GitHub Actions Runner OS Versions JSON

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 00:00 运行
  workflow_dispatch: # 允许手动触发

env:
  JSON_FILE_PATH: ${{ github.workspace }}/runner-images.json

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install axios

      - name: Run script to generate JSON
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const axios = require('axios');
  
            const GITHUB_REPO = 'actions/runner-images';
  
            async function fetchReadme() {
                const url = `https://api.github.com/repos/${GITHUB_REPO}/contents/README.md`;
                const response = await axios.get(url, {
                    headers: { 'Accept': 'application/vnd.github.v3.raw' }
                });
                return response.data;
            }
  
            function parseOSVersions(content) {
                const tableStart = content.indexOf('| Image | YAML Label |');
                const tableEnd = content.indexOf('\n\n', tableStart);
                const tableContent = content.slice(tableStart, tableEnd);
  
                const lines = tableContent.split('\n').filter(line => line.trim().startsWith('|'));
  
                const headers = lines[0]
                    .split('|')
                    .slice(1, -1)
                    .map(header => header.trim());
  
                const data = lines.slice(2).map(line => {
                    const cells = line
                        .split('|')
                        .slice(1, -1)
                        .map(cell => cell.trim());
  
                    return headers.reduce((obj, header, index) => {
                        obj[header] = cells[index];
                        return obj;
                    }, {});
                });
  
                const categories = {
                    ubuntu: [],
                    windows: [],
                    macos: [],
                    other: []
                };
  
                data.forEach(item => {
                    const image = item.Image.replace(/<sup>.*?<\/sup>/g, '').trim();
                    const yamlLabel = item['YAML Label'].replace(/`/g, '').trim();
  
                    const entry = { image, yamlLabels: parseYamlLabel(yamlLabel) };
  
                    if (image.includes('Ubuntu')) {
                        categories.ubuntu.push(entry);
                    } else if (image.includes('Windows')) {
                        categories.windows.push(entry);
                    } else if (image.includes('macOS')) {
                        categories.macos.push(entry);
                    } else {
                        categories.other.push(entry);
                    }
                });
  
                return {
                    categories,
                    updated: new Date().toISOString()
                };
            }
  
            function parseYamlLabel(yamlLabel) {
                return yamlLabel
                    .split(' or ')
                    .map(label => label.split(','))
                    .flat()
                    .map(label => label.trim())
                    .map(label => label.replace(/`/g, ''))
                    .filter(label => label.length > 0);
            }
  
            (async ()=>{
                try {
                    const readmeContent = await fetchReadme();
                    const data = parseOSVersions(readmeContent);
                
                    // 将数据写入 JSON 文件
                    fs.writeFileSync(process.env.JSON_FILE_PATH, JSON.stringify(data, null, 2));
                    console.log(`JSON 文件已生成：${process.env.JSON_FILE_PATH}`);
                } catch (error) {
                    console.error('Error:', error.message);
                    process.exit(1);
                }
            })();

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add runner-images.json
          git commit -m "Auto-generated JSON file [skip ci]"
          git push
